### ISSUE TITLE
Crash on startup [1.20.1]

### ISSUE THREAD

**Issue by mpustovoi** [anviaan/BedrockPlus#11]
On Modrinth the version "**Bedrock Plus-1.19.4-1.6**" is incompatible with 1.20.1 despite the fact that the opposite is stated and causes this error on startup:
`java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'bedrockplus'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
	at net.minecraft.class_310.<init>(class_310.java:458)
	at net.minecraft.client.main.Main.main(Main.java:211)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.NoSuchMethodError: 'net.minecraft.class_1761$class_7913 net.fabricmc.fabric.api.itemgroup.v1.FabricItemGroup.builder(net.minecraft.class_2960)'
	at net.anvian.bedrockplus.item.ModItemGroup.registerItemGroup(ModItemGroup.java:14)
	at net.anvian.bedrockplus.BedrockPlusMod.onInitialize(BedrockPlusMod.java:21)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	... 7 more`
Please change its version because it breaks my 1.20.1 modpack every time I update it.
![image](https://github.com/anviaan/BedrockPlus/assets/92390626/ea42ef8b-50a8-4e62-9e20-315d50083d84)

**Comment by mpustovoi** [comment]
https://github.com/anviaan/BedrockPlus/issues/10

**Comment by mpustovoi** [comment]
https://github.com/anviaan/BedrockPlus/issues/10#issue-1908695819

**Comment by mpustovoi** [comment]
https://github.com/anviaan/BedrockPlus/issues/10#issue-1908695819

**Comment by mpustovoi** [comment]
The same problem is mentioned in https://github.com/anviaan/BedrockPlus/issues/10

**Comment by anviaan** [comment]
Checking the project I saw that there was an error in uploading the mod for version 1.19.4.
Version 1.20 has its own jar file and so does 1.19.4. Both are separate, I recommend you to download the appropriate version for the version you are using. Sorry for the inconvenience

**Comment by mpustovoi** [comment]
Yes, I download the version for 1.20.1 every time.
The fact is that since version 1.19.4 is higher in the list, when updating my modpack I have to manually download the version for 1.20.1 again.
Maybe it's worth re-releasing version 1.19.4 so that there is no misunderstanding in the future?

**Comment by mpustovoi** [comment]
Thank you for the prompt correction!
